import SFIcon from './SFIcon';

export const ICON_MAP = {
  housing:       { icon: 'house.svg',                          color: '#007AFF' },
  groceries:     { icon: 'cart.svg',                           color: '#34C759' },
  transport:     { icon: 'car.svg',                            color: '#FF9500' },
  health:        { icon: 'pill.svg',                           color: '#FF2D55' },
  entertainment: { icon: 'gamecontroller.svg',                 color: '#AF52DE' },
  clothing:      { icon: 'tshirt.svg',                         color: '#FF6B81' },
  subscriptions: { icon: 'iphone.svg',                        color: '#5AC8FA' },
  dining:        { icon: 'fork.knife.svg',                     color: '#FF6900' },
  education:     { icon: 'book.closed.svg',                    color: '#5856D6' },
  gifts:         { icon: 'giftcard.svg',                       color: '#FF3B30' },
  other:         { icon: 'questionmark.folder.svg',            color: '#8E8E93' },
  salary:        { icon: 'dollarsign.svg',                     color: '#34C759' },
  investment:    { icon: 'chart.line.uptrend.xyaxis.svg',      color: '#007AFF' },
  extra:         { icon: 'bolt.svg',                           color: '#FF9500' },
  transfer:      { icon: 'arrow.left.arrow.right.svg',         color: '#8E8E93' },
  cash:          { icon: 'banknote.svg',                       color: '#30D158' },
  internet:      { icon: 'wifi.svg',                           color: '#5AC8FA' },
  gym:           { icon: 'figure.strengthtraining.traditional.svg', color: '#FF6900' },
  music:         { icon: 'music.note.list.svg',                color: '#FF2D55' },
  coffee:        { icon: 'cup.and.saucer.svg',                 color: '#AC8E68' },
  cloud:         { icon: 'icloud.svg',                         color: '#5AC8FA' },
  design:        { icon: 'paintbrush.svg',                     color: '#AF52DE' },
  // DB category keys
  food:          { icon: 'fork.knife.svg',                     color: '#FF6900' },
  shopping:      { icon: 'bag.svg',                            color: '#EC4899' },
  travel:        { icon: 'airplane.svg',                       color: '#06B6D4' },
  personal:      { icon: 'person.svg',                         color: '#F97316' },
  pets:          { icon: 'pawprint.svg',                       color: '#84CC16' },
  family:        { icon: 'figure.and.child.holdinghands.svg',  color: '#F43F5E' },
  financial:     { icon: 'banknote.svg',                       color: '#64748B' },
  freelance:     { icon: 'briefcase.svg',                      color: '#059669' },
  investments:   { icon: 'chart.line.uptrend.xyaxis.svg',      color: '#3B82F6' },
  rental:        { icon: 'house.svg',                          color: '#8B5CF6' },
  extra_income:  { icon: 'bolt.svg',                           color: '#F59E0B' },
  // subcategories
  rent:          { icon: 'house.svg',                          color: '#4F8EF7' },
  mortgage_pay:  { icon: 'building.svg',                       color: '#4F8EF7' },
  utilities:     { icon: 'lightbulb.svg',                      color: '#FCD34D' },
  home_insurance:{ icon: 'shield.svg',                         color: '#93C5FD' },
  maintenance:   { icon: 'wrench.and.screwdriver.svg',         color: '#A3A3A3' },
  furniture:     { icon: 'sofa.svg',                           color: '#D97706' },
  dining_out:    { icon: 'fork.knife.svg',                     color: '#F97316' },
  takeaway:      { icon: 'takeoutbag.and.cup.and.straw.svg',   color: '#FB923C' },
  bakery:        { icon: 'basket.svg',                         color: '#FDE68A' },
  fuel:          { icon: 'fuelpump.svg',                       color: '#FFB800' },
  public_transit:{ icon: 'bus.svg',                            color: '#FBBF24' },
  car_insurance: { icon: 'car.front.waves.down.svg',           color: '#D97706' },
  car_maintenance:{ icon: 'wrench.and.screwdriver.svg',        color: '#B45309' },
  parking:       { icon: 'parkingsign.svg',                    color: '#92400E' },
  taxi_uber:     { icon: 'car.svg',                            color: '#F59E0B' },
  doctor:        { icon: 'stethoscope.svg',                    color: '#FF4757' },
  pharmacy:      { icon: 'pill.svg',                           color: '#F87171' },
  dentist:       { icon: 'stethoscope.svg',                    color: '#FCA5A5' },
  mental_health: { icon: 'heart.svg',                          color: '#FECACA' },
  streaming:     { icon: 'tv.svg',                             color: '#A855F7' },
  games:         { icon: 'gamecontroller.svg',                 color: '#9333EA' },
  cinema:        { icon: 'film.stack.svg',                     color: '#7C3AED' },
  concerts:      { icon: 'music.note.list.svg',                color: '#6D28D9' },
  sports:        { icon: 'soccerball.svg',                     color: '#5B21B6' },
  hobbies:       { icon: 'paintbrush.svg',                     color: '#DDD6FE' },
  electronics:   { icon: 'laptopcomputer.svg',                 color: '#DB2777' },
  books:         { icon: 'book.svg',                           color: '#BE185D' },
  home_goods:    { icon: 'archivebox.svg',                     color: '#9D174D' },
  flights:       { icon: 'airplane.svg',                       color: '#06B6D4' },
  hotels:        { icon: 'bed.double.svg',                     color: '#0891B2' },
  car_rental:    { icon: 'car.svg',                            color: '#0E7490' },
  activities:    { icon: 'map.svg',                            color: '#155E75' },
  courses:       { icon: 'laptopcomputer.svg',                 color: '#8B5CF6' },
  tuition:       { icon: 'graduationcap.svg',                  color: '#7C3AED' },
  books_edu:     { icon: 'book.closed.svg',                    color: '#6D28D9' },
  workshops:     { icon: 'wrench.and.screwdriver.svg',         color: '#5B21B6' },
  haircut:       { icon: 'scissors.svg',                       color: '#F97316' },
  skincare:      { icon: 'sun.max.svg',                        color: '#FB923C' },
  clothing_care: { icon: 'tshirt.svg',                         color: '#FED7AA' },
  software_sub:  { icon: 'laptopcomputer.svg',                 color: '#0EA5E9' },
  music_sub:     { icon: 'music.note.list.svg',                color: '#0284C7' },
  video_sub:     { icon: 'tv.svg',                             color: '#0369A1' },
  news_sub:      { icon: 'newspaper.svg',                      color: '#075985' },
  cloud_sub:     { icon: 'icloud.svg',                         color: '#0C4A6E' },
  pet_food:      { icon: 'pawprint.svg',                       color: '#84CC16' },
  vet:           { icon: 'stethoscope.svg',                    color: '#65A30D' },
  pet_grooming:  { icon: 'scissors.svg',                       color: '#4D7C0F' },
  childcare:     { icon: 'figure.and.child.holdinghands.svg',  color: '#F43F5E' },
  school:        { icon: 'graduationcap.svg',                  color: '#E11D48' },
  allowance:     { icon: 'dollarsign.svg',                     color: '#BE123C' },
  bank_fees:     { icon: 'building.svg',                       color: '#64748B' },
  insurance:     { icon: 'shield.svg',                         color: '#475569' },
  taxes:         { icon: 'gear.svg',                           color: '#334155' },
  savings_transfer: { icon: 'banknote.svg',                    color: '#1E293B' },
  gifts_out:     { icon: 'giftcard.svg',                       color: '#EF4444' },
  charity:       { icon: 'heart.svg',                          color: '#DC2626' },
  main_salary:   { icon: 'dollarsign.svg',                     color: '#10B981' },
  bonus:         { icon: 'trophy.svg',                         color: '#059669' },
  holiday_pay:   { icon: 'sun.max.svg',                        color: '#047857' },
  consulting:    { icon: 'briefcase.svg',                      color: '#059669' },
  side_project:  { icon: 'gear.svg',                           color: '#047857' },
  dividends:     { icon: 'chart.bar.xaxis.ascending.svg',      color: '#3B82F6' },
  crypto_profit: { icon: 'bitcoinsign.svg',                    color: '#1D4ED8' },
  stock_profit:  { icon: 'chart.line.uptrend.xyaxis.svg',      color: '#1E40AF' },
  cashback:      { icon: 'creditcard.svg',                     color: '#F59E0B' },
  gift_received: { icon: 'giftcard.svg',                       color: '#D97706' },
  tax_return:    { icon: 'gear.svg',                           color: '#B45309' },
  government:    { icon: 'building.2.svg',                     color: '#92400E' },
};

export default function CategoryIcon({ category, size = 36 }) {
  const entry = ICON_MAP[category] || ICON_MAP.other;
  const { icon, color } = entry;
  const iconSize = Math.round(size * 0.5);

  return (
    <div style={{
      width: size,
      height: size,
      borderRadius: Math.round(size * 0.26),
      background: color + '18',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      flexShrink: 0,
    }}>
      <SFIcon name={icon} size={iconSize} color={color} />
    </div>
  );
}
